# default_language_version:
#   python: python3.13.5

# default_stages: [pre-commit, pre-push]

# default_install_hook_types:
#   - pre-commit
#   - commit-msg
#   - pre-push

# repos:
  # - repo: https://github.com/MarcoGorelli/absolufy-imports
  #   rev: v0.3.1
  #   hooks:
  #       - id: absolufy-imports
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v4.2.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages: [commit-msg]
  #       args: [--strict, feat, fix, docs, test, ci, refactor, perf, chore, revert]
  # - repo: local
  #   hooks:
  #     - id: lint
  #       name: lint
  #       entry: make lint
  #       language: system
  #       types: [ python ]
  #       pass_filenames: false
  #     - id: secure
  #       name: secure
  #       entry: make secure
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #     - id: pytype
  #       name: pytype
  #       entry: make type-check
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #     - id: check-branch-name
  #       name: check-branch-name
  #       entry: make check-branch-name
  #       language: system
  #       pass_filenames: false
  #     - id: check-coverage
  #       name: check-coverage
  #       entry: make test-cov
  #       language: system
  #       pass_filenames: false