services:
  service:
    image: core-service
    container_name: core-service
    restart: always
    build:
      context: .
      dockerfile: ./ci/api.Dockerfile
    volumes:
      - .:/b2broker-task
      - ./logs:/b2broker-task/logs
    env_file:
      - .env
    entrypoint:
      - /entrypoints/start.gunicorn.sh
    ports:
      - 8000:8000
    depends_on:
      - postgres


  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./ci/db.Dockerfile
    env_file:
      - .env
    volumes: 
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  

networks:
  default:
    name: b2broker_default